[Section 2] methods in ruby
Michelle-Lohwt/Learn-Ruby-on-Rails pull request #9
Opened 2021-11-14 03:30 UTC by Michelle-Lohwt

- Learning how to use methods in ruby

2021-11-14 09:29 UTC, tlkiong reviewed
Why do you need to do `.to_f` in all the method?
Why not `.to_i`?

2021-11-14 11:29 UTC, Michelle-Lohwt commented
If you put `.to_i`, you might not get the correct ans (the system most likely will floor the number before any operation, example: `first = 2.5`, `second = 1`, `multiply(first, second) = 2`)

2021-11-14 13:08 UTC, tlkiong requested changes
2 spaces indent?
And no empty spaces that does nothing?

To build a masterpiece, start from the details

2021-11-14 14:55 UTC, Michelle-Lohwt commented
What does this mean?

> And no empty spaces that does nothing?

2021-11-14 23:08 UTC, tlkiong commented on sec2_the-ruby-programming-language/2.5_methods.rb
> +                                # hence no need to explicitly call "return"
```suggestion
    # automatically return the last line, 
    # hence no need to explicitly call "return"
    first.to_f * second.to_f    
```

Put comments to the top

2021-11-15 02:32 UTC, tlkiong approved these changes

2021-11-15 02:33 UTC, merged